version: "3.7"

networks:
    local:

services:

    postgres:
        container_name: ${COMPOSE_PROJECT_NAME}_postgres
        user: ${UID}:${GID}
        image: postgres:15-alpine
        restart: unless-stopped
        volumes:
            - /etc/passwd:/etc/passwd:ro # change users for db initialization
            - ./data/postgres:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            # life hack. In this case postgres create subdirectory for files, which created from container and non root user
            - PGDATA=/var/lib/postgresql/data/_data
        ports:
            - "${DB_PORT_EXTERNAL}:5432"
        networks:
            - local


    redis:
        container_name: ${COMPOSE_PROJECT_NAME}_redis
#        user: ${UID}:${GID}
        image: redis:7-alpine
        restart: unless-stopped
        ports:
            - "${REDIS_PORT_EXTERNAL}:6379"
        volumes:
            - ./data/redis:/data
        networks:
            - local

    php: &app
        container_name: ${COMPOSE_PROJECT_NAME}_php
        user: ${UID}:${GID}
        build:
            context: ./php
            dockerfile: ./Dockerfile
        expose:
            - 9000
        restart: unless-stopped
        depends_on:
            - postgres
        volumes:
            - ${PROJECT_ROOT}:/var/www
            - ./php/php.ini:/usr/local/etc/php/php.ini
        environment:
            - MC_PROFILE_ROOT:/tmp
        networks:
            - local

#    Scheduler run
#    php_schedule:
#        <<: *app
#        container_name: ${COMPOSE_PROJECT_NAME}_php_schedule
#        entrypoint: [ 'php', '/var/www/artisan', 'schedule:work' ]
#        expose: [ ]
#        restart: unless-stopped
#    Queue "default","notification","telegram"
#    php_queue_default:
#        <<: *app
#        container_name: ${COMPOSE_PROJECT_NAME}_php_queue_default
#        entrypoint: [ 'php', '/var/www/artisan', 'queue:work' ]
#        expose: [ ]
#        restart: unless-stopped
#    php_queue_notification:
#        <<: *app
#        container_name: ${COMPOSE_PROJECT_NAME}_php_queue_notification
#        entrypoint: [ 'php', '/var/www/artisan', 'queue:work', 'notification' ]
#        expose: [ ]
#        restart: unless-stopped
#    php_queue_telegram:
#        <<: *app
#        container_name: ${COMPOSE_PROJECT_NAME}_php_queue_telegram
#        entrypoint: [ 'php', '/var/www/artisan', 'queue:work', 'telegram' ]
#        expose: [ ]
#        restart: unless-stopped
#    php_queue_distributing:
#        <<: *app
#        container_name: ${COMPOSE_PROJECT_NAME}_php_queue_distributing
#        entrypoint: [ 'php', '/var/www/artisan', 'queue:work', 'distributing' ]
#        expose: [ ]
#        restart: unless-stopped


    nginx:
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        image: nginx:alpine
        restart: unless-stopped
        depends_on:
            - php
        ports:
            - ${NGINX_PORT_EXTERNAL}:80
        volumes:
            - ${PROJECT_ROOT}:/var/www
            - ./nginx/local.conf:/etc/nginx/conf.d/default.conf
            - ./data/nginx/logs:/var/log/nginx
        networks:
            - local

#    service for mail catching
#    mailpit:
#        container_name: ${COMPOSE_PROJECT_NAME}_mailpit
#        image: axllent/mailpit
#        restart: unless-stopped
#        ports:
#            - "1025:1025"
#            - "8025:8025"
#        networks:
#            - local

#    service for work with frontend
    node:
        container_name: ${COMPOSE_PROJECT_NAME}_node
        user: ${UID}:${GID}
        tty: true
        build:
            context: ./node
            dockerfile: ./Dockerfile
        volumes:
            - ${PROJECT_ROOT}:/var/www

#    service for attaching an external domain to a local computer
#    fill variables NGROK_AUTHTOKEN and NGROK_USER_DOMAIN in docker env
    ngrok:
        image: ngrok/ngrok:latest
        container_name: ${COMPOSE_PROJECT_NAME}_ngrok
        restart: unless-stopped
        environment:
            NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
        command:
            - "http"
            - "${COMPOSE_PROJECT_NAME}_nginx:${NGINX_PORT_EXTERNAL}"
            - "--domain"
            - "${NGROK_USER_DOMAIN}"
        ports:
            - 4040:4040
        networks:
          - local
